### ISSUE TITLE
`ValidationError: Product validation failed` error when running `npm run db:seed`

### ISSUE THREAD

**Issue by foyzulkarim** [foyzulkarim/rbac-mern-boilerplate#1]
When I run `npm run db:seed` to seed the database, it is giving me below error. 

![image](https://user-images.githubusercontent.com/497812/134109913-13c7b20e-f412-4eb3-917f-537cc14ef465.png)

You can get hits how to solve this in this video: https://youtu.be/UhXjemzbNSs?t=1192

Full terminal output:
```sh
> server@1.0.0 db:seed /Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server
> node ./setup/seed-products.js

Seed starting
mongodb://localhost:27017/appdb
Seed finished
(node:32458) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Database connection established
/Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/document.js:2760
    this.$__.validationError = new ValidationError(this);
                               ^

ValidationError: Product validation failed: size: Path `size` is required., expiryDate: Path `expiryDate` is required., manufacturingDate: Path `manufacturingDate` is required., description: Path `description` is required.
    at model.Document.invalidate (/Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/document.js:2760:32)
    at /Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/document.js:2552:17
    at /Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  errors: {
    size: ValidatorError: Path `size` is required.
        at validate (/Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1270:13)
        at /Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1253:7
        at Array.forEach (<anonymous>)
        at SchemaNumber.SchemaType.doValidate (/Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1198:14)
        at /Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/document.js:2545:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
        at runNextTicks (node:internal/process/task_queues:65:3)
        at processImmediate (node:internal/timers:437:9) {
      properties: {
        validator: [Function (anonymous)],
        message: 'Path `size` is required.',
        type: 'required',
        path: 'size',
        value: undefined
      },
      kind: 'required',
      path: 'size',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    expiryDate: ValidatorError: Path `expiryDate` is required.
        at validate (/Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1270:13)
        at /Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1253:7
        at Array.forEach (<anonymous>)
        at SchemaDate.SchemaType.doValidate (/Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1198:14)
        at /Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/document.js:2545:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
        at runNextTicks (node:internal/process/task_queues:65:3)
        at processImmediate (node:internal/timers:437:9) {
      properties: {
        validator: [Function (anonymous)],
        message: 'Path `expiryDate` is required.',
        type: 'required',
        path: 'expiryDate',
        value: undefined
      },
      kind: 'required',
      path: 'expiryDate',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    manufacturingDate: ValidatorError: Path `manufacturingDate` is required.
        at validate (/Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1270:13)
        at /Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1253:7
        at Array.forEach (<anonymous>)
        at SchemaDate.SchemaType.doValidate (/Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1198:14)
        at /Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/document.js:2545:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
        at runNextTicks (node:internal/process/task_queues:65:3)
        at processImmediate (node:internal/timers:437:9) {
      properties: {
        validator: [Function (anonymous)],
        message: 'Path `manufacturingDate` is required.',
        type: 'required',
        path: 'manufacturingDate',
        value: undefined
      },
      kind: 'required',
      path: 'manufacturingDate',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    },
    description: ValidatorError: Path `description` is required.
        at validate (/Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1270:13)
        at /Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1253:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (/Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/schematype.js:1198:14)
        at /Users/foyzul/Documents/foyzul/github/rbac-mern-boilerplate/server/node_modules/mongoose/lib/document.js:2545:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
        at runNextTicks (node:internal/process/task_queues:65:3)
        at processImmediate (node:internal/timers:437:9) {
      properties: {
        validator: [Function (anonymous)],
        message: 'Path `description` is required.',
        type: 'required',
        path: 'description',
        value: undefined
      },
      kind: 'required',
      path: 'description',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'Product validation failed'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 db:seed: `node ./setup/seed-products.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.0.0 db:seed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/foyzul/.npm/_logs/2021-09-21T03_52_39_643Z-debug.log
```

**Comment by foyzulkarim** [comment]
Issue is fixed for now. Thanks to @minhajul-karim brother.

**Comment by dvs110** [comment]
in this u have to check the "name" field in html with parameters of schema
console.log(req.body)
{email: ga@gmail.com,
password: gfg
}
this email and pass should be same as name fields in html
 html=>
<form class="form" action="/form" method="post">
      <div class="inputfield">
        <label>Password</label>
        <input type="password" class="input" name="password" required>
      </div>
      <div class="inputfield">
        <label>Email Address</label>
        <input type="email" class="input" name="email" required>
      </div>
</form>
